### PR TITLE
To otilrac (Please readme)

### PR DESCRIPTION
**Pull request by SteveJayH**

### CODE REVIEW

**Comment by SteveJayH** [comment]
Hi otilrac,

Can you check my commit? It seems like you are using Github but maybe you didn't read my message yet...

**Comment by SteveJayH** [comment]
Hi otilrac,

Can you check this??? It was my mistake to upload some photos (for testing the code) and make it public, and you have forked that version of my code. There are not only my photos, my friends' so that I want to remove them on the internet. Sorry for this situation and if it is possible, please delete the repo from your github....

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Comment by otilrac** [comment]
Hello SteveJayH, i have removed the photo from the fork. Best Regards

**Pull request closed without merging**
